# Generated by Django 4.1.2 on 2022-10-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='icon',
        ),
    ]
