# Generated by Django 4.1.2 on 2022-10-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='github_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hunter',
        ),
        migrations.RemoveField(
            model_name='project',
            name='votes_total',
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
